modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="soe"
version="1.0.0"
displayName="Spirit Of Enium"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="Swelkinn_n, MCreator"
description='''
Everything, Anything, and More
'''

[[dependencies.soe]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




